default: &default
  adapter: sqlite3
  encoding: utf8
  host: <%= ENV["DATABASE_HOST"] %>
  pool: <%= ENV["DATABASE_POOL_SIZE"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  database: db/development.sqlite3
  <<: *default

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  database: <%= ENV["DATABASE_NAME"] %>

  <<: *default
